<option value="#FFFFFF">Blanc</option>
<option value="#F5F5DC">Belge</option>
<option value="#0000FF">Bleu</option>
<option value="#00CED1">Bleu Claire</option>
<option value="#1E90FF">Bleu Ciel</option>
<option value="#00FFFF">Bleu Marin</option>
<option value="#BDB76B">Dnaki</option>
<option value="#708090">Gris</option>
<option value="#FFFF33">Jaune</option>
<option value="#8B4513">Maron</option>
<option value="#CD853F">Maron Claire</option>
<option value="#000000">Noir</option>
<option value="#FFD700">Orange</option>
<option value="#FF4500">Orange Foncé</option>
<option value="#FF33CC">Rose</option>
<option value="#FF3399">Rose  Claire</option>
<option value="#FF69B4">Rose Sombre</option>
<option value="#FF1493">Rose Vif</option>
<option value="#FF0000">Rouge</option>
<option value="#F08080">Rouge Claire</option>
<option value="#800000">Rouge Sombre</option>
<option value="#008000">Vert</option>
<option value="#90EE90">Vert Claire</option>
<option value="#808000">Vert Olive</option>
<option value="#FFC0CB">Violet</option>
<option value="#DA70D6">Violet  Claire</option>
<option value="#9400D3">Violet Vif</option>
<option value="#660066">Violet Sombre</option>
